version: '3'
services:
  web:
     build:
        context: ./
        dockerfile: ./docker/web/Dockerfile
     environment:
       - ALLOW_OVERRIDE=true
     ports:
       - "80:80"
     links:
       - db
     volumes:
       - ./app:/var/www/html/
     container_name: spagnesi_web


  db:
    build: ./docker/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cartiamotwig
    ports:
      - "3306:3306"
    container_name: spagnesi_db
    
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - db:mysql
    ports:
      - "8181:80"
    environment:
      MYSQL_USERNAME: admin
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PORT_3306_TCP_ADDR: db

  composer:
      image: composer
      volumes:
        - ./app:/app
      command: install
